### ISSUE TITLE
Build Error for v1.3

### ISSUE THREAD

**Issue by Vaelatern** [patroclos/PAmix#11]
```
./configure: line 2900: syntax error near unexpected token `,mandatory'
./configure: line 2900: `AX_CXX_COMPILE_STDCXX_11(,mandatory)'
```

This appears to be due to one of the first lines in `./configure.ac`.

**Comment by Vaelatern** [comment]
I fixed that one, now fixing another one.

**Comment by patroclos** [comment]
This is quite strange, as nothing changed about the configure.ac script.
Did you run `autoreconf -i`?

**Comment by Vaelatern** [comment]
Yes. I believe it to be an artifact of the build environment not having all the required parts around. Do you perhaps have a dependency on m4?

**Comment by Vaelatern** [comment]
This is while updating the Void Linux package

**Comment by Vaelatern** [comment]
Currently suspect an unspoken dependency on m4.

**Comment by Vaelatern** [comment]
Yes. Really unsure as to what is wrong here.

**Comment by Vaelatern** [comment]
My version:
`autoreconf (GNU Autoconf) 2.69`

**Comment by patroclos** [comment]
Well, thats even stranger, as I have the same version

**Comment by Vaelatern** [comment]
Same issue for `autoreconf -fi` and `autoreconf -i`

**Comment by patroclos** [comment]
I think the latest commit should fix things for you, since your problem only seems to be with the arguments

**Comment by Vaelatern** [comment]
When I apply your latest commit, d102ab2, I get a similar error:

```
checking for a BSD-compatible install... /builddir/.xbps-PAmix/wrappers/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
./configure: line 2903: syntax error near unexpected token `ac_ext=cpp'
./configure: line 2903: `ac_ext=cpp'
```

Which is 3 lines after `AX_CXX_COMPILE_STDCXX_11()` is present in the configure script. I don't know if that is intentional.

**Comment by Vaelatern** [comment]
My autotools complains when I change the patch:

```
./configure: line 2900: syntax error near unexpected token `11'
./configure: line 2900: `AX_CXX_COMPILE_STDCXX(11)'
```

From reading the docs it seems this should not be an issue.
Perhaps some m4 settings need tuning?

**Comment by patroclos** [comment]
I think you may be required to surround the arguments in rectangular brackets
for example: `AX_CXX_COMPILE_STDCXX([11], [noext], [mandatory])`

**Comment by Vaelatern** [comment]
This was after I did so.

**Comment by patroclos** [comment]
so did you change something regarding autoconf and/or was the configure script working for you prior to 1.3?

**Comment by Vaelatern** [comment]
In 1.2 only a makefile was used. Basically, both of these invocations failed: `AX_CXX_COMPILE_STDCXX([11])`
`AX_CXX_COMPILE_STDCXX(11)`

**Comment by patroclos** [comment]
Oh, I was assuming you were on the master branch.
I was able to reproduce your issue, you need to install autoconf-archive and reconfigure

**Comment by Vaelatern** [comment]
Excellent! Thank you!

**Comment by Cheaterman** [comment]
Thanks for the simple answer, I ran into this today - this is a relatively uptodate Gentoo, probably the autoconf-archive package is simply missing from the current ebuild dependencies. :-)

**Comment by patroclos** [comment]
@Cheaterman Thats strange, autoconf-archive should be in ebuild dependencies since [this](https://bugs.gentoo.org/show_bug.cgi?id=593682) bug

**Comment by Cheaterman** [comment]
@patroclos Thanks a lot for your answer and interest! I can confirm that my other computers' Portage trees all include ebuilds that properly depend on `sys-devel/autoconf-archive`, so I guess my Portage tree on that machine was much more outdated than I expected. Sorry for the bump everyone, my bad!
