### ISSUE TITLE
PAmix should exit gracefully when no pulseaudio is running.

### ISSUE THREAD

**Issue by Polynomial-C** [patroclos/PAmix#21]
When no pulseaudio is running and PAmix is being started the whole terminal turns blank and no key event seems to work. Pressing `q` to quit PAmix has no effect. Only pressing `CTRL+C` exits PAmix. Please let PAmix exit gracefully when it cannot find or connect to any pulseaudio instance/daemon preferrably with a user-friendly (error)message.

**Comment by patroclos** [comment]
this should already be the case, ill look into it

**Comment by Polynomial-C** [comment]
Alright, this is some obscure issue with my environment setting `DISPLAY="localhost:10.0"` somewhere again. Once I run `DISPLAY="" pamix` everything works.
Sorry for yet another confusing bug report from me.
