### ISSUE TITLE
Fails to compile - src/pamix.cpp:8:30: fatal error: ncursesw/ncurses.h: No such file or directory

### ISSUE THREAD

**Issue by ColdfireDI** [patroclos/PAmix#23]
this issue is also listed on the AUR https://aur.archlinux.org/packages/pamix-git/ is this package going to be updated?

src/pamix.cpp:8:10: fatal error: ncursesw/ncurses.h: No such file or directory                      
 #include <ncursesw/ncurses.h>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.  
make[1]: *** [Makefile:569: src/pamix-pamix.o] Error 1                                              
make[1]: Leaving directory '/home/coldfire/.cache/pacaur/pamix-git/src/PAmix'                       
make: *** [Makefile:350: all] Error 2             
==> ERROR: A failure occurred in build().         
    Aborting...          
:: failed to build pamix-git package(s)

**Comment by patroclos** [comment]
if i am not mistaken you can swap out the include directive with '#include <ncurses.h>' on arch

**Comment by pickfire** [comment]
Yes, it works after I replaced `#include <ncursesw/ncurses.h>` with `#include <ncurses.h>`.

By the way, the build fails on arch without installing `autoconf-archive`, should we specify that in PKGBUILD?

**Comment by patroclos** [comment]
yeah, `autoconf-archive` is a build dependency.
I dont know yet how to handle the distro-specific header locations...
The includedir variable in the .pc file doesnt seem to be of any help
