### ISSUE TITLE
Release 1.5 tagged version is  pointing to configure that still includes 1.2

### ISSUE THREAD

**Issue by noahfx** [patroclos/PAmix#26]
Hi,

I did noticed that the release 1.5 points to the commit https://github.com/patroclos/PAmix/commit/cccd278e14989bddad80fb1581078bc094ad3baf and the pamix version is bumped until https://github.com/patroclos/PAmix/commit/110bb54f0055dc2e83b526e6167e7c5df007accd 

Regards

**Comment by patroclos** [comment]
Would you propose to alter the tag or just add a new tag for 1.5.1 or something along those lines?
