### ISSUE TITLE
Compile issue Opensuse 13.2 libtinfo.so error

### ISSUE THREAD

**Issue by Mirppc** [patroclos/PAmix#3]
So i tried compiling on Opensuse 13.2 64bit and ran into an issue when issuing the make command.

`~/bin/PAmix> make
g++ -Wall -O2 -std=c++11 -Iinclude -g -pthread -c src/pamix.cpp -o build/pamix.o
g++ -Wall -O2 -std=c++11 -Iinclude -g -pthread -c src/painterface.cpp -o build/painterface.o
g++ -Wall -O2 -std=c++11 -Iinclude -g -pthread -lncursesw -lpulse build/pamix.o build/painterface.o -o bin/pamix
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: /lib64/libncursesw.so.5: undefined reference to symbol 'LINES'
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../lib64/libtinfo.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:20: recipe for target 'bin/pamix' failed
make: *** [bin/pamix] Error 1
`

I will check to see if i have the devel for libtinfo as i know i have the ncurses devel files. 

EDIT: Checked and that isnt it.

**Comment by patroclos** [comment]
Thanks for your report!
I think this could be related to a previous issue, could you pull the newest changes and retry?

**Comment by Mirppc** [comment]
Thanks for the swift response.  Didnt work sadly T_T

`~/bin/PAmix> git clone https://github.com/patroclos/PAmix.git PAmix
Cloning into 'PAmix'...
remote: Counting objects: 173, done.
remote: Compressing objects: 100% (76/76), done.
remote: Total 173 (delta 37), reused 0 (delta 0), pack-reused 95
Receiving objects: 100% (173/173), 33.47 KiB | 0 bytes/s, done.
Resolving deltas: 100% (83/83), done.
Checking connectivity... done.
         ~/bin/PAmix> make
g++ -Wall -O2 -std=c++11 -Iinclude -g -pthread -lncursesw -lpulse build/pamix.o build/painterface.o -o bin/pamix
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: /lib64/libncursesw.so.5: undefined reference to symbol 'LINES'
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../lib64/libtinfo.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:20: recipe for target 'bin/pamix' failed
make: *** [bin/pamix] Error 1
`

**Comment by patroclos** [comment]
you ran the old Makefile again and you made another clone instead of a pull.
try the following:
~/bin/PAmix> rm -rf PAmix
~/bin/PAmix> git pull origin master
~/bin/PAmix> make

**Comment by Mirppc** [comment]
`~/bin/PAmix> make
g++ -Wall -O2 -std=c++11 -Iinclude -pthread -D_REENTRANT -I/usr/include/ncursesw -I/usr/include/ncurses  -c src/pamix.cpp -o build/pamix.o
g++ -Wall -O2 -std=c++11 -Iinclude -pthread -D_REENTRANT -I/usr/include/ncursesw -I/usr/include/ncurses  -c src/painterface.cpp -o build/painterface.o
g++ -Wall -O2 -std=c++11 -Iinclude -pthread -D_REENTRANT -I/usr/include/ncursesw -I/usr/include/ncurses  -lpulse -lncursesw -ltinfo  build/pamix.o build/painterface.o -o bin/pamix
`
That worked.  I did the git clone to the wrong directory.
