### ISSUE TITLE
Release 1.6 deleted?

### ISSUE THREAD

**Issue by avindra** [patroclos/PAmix#34]
Hey, noticed 1.6 went up and now it's gone, which is causing builds to fail.

**Comment by patroclos** [comment]
Yeah sorry for that, I didn't realize it was already packaged, I looked on repology.org beforehand.
There were still an issue I didn't want in the release, I'll re-release in a couple of hours.

BTW, for which repository are you packaging?

**Comment by patroclos** [comment]
[1.6](https://github.com/patroclos/PAmix/releases/tag/1.6) is now up again

**Comment by avindra** [comment]
@patroclos I'm packing it for openSUSE

https://build.opensuse.org/package/show/multimedia:libs/pamix

openSUSE Tumbleweed users will be able to just `zypper install pamix` once this gets approved and merged:

https://build.opensuse.org/request/show/560952

**Comment by avindra** [comment]
Since 1.6 is back, I'll close this out.

Thanks! I'm subscribed to updates for PAmix btw, so I'll push them out to suse when I can.
