### ISSUE TITLE
Start of pamix fails

### ISSUE THREAD

**Issue by Polynomial-C** [patroclos/PAmix#5]
This is all I get when running pamix in either bash or zsh:

```
pamix: src/painterface.cpp:67: PAInterface::PAInterface(const char*): Assertion `pa_context_connect(m_Context, __null, PA_CONTEXT_NOAUTOSPAWN, __null) == 0' failed.
    zsh: abort      LANG="C" pamix
```

**Comment by patroclos** [comment]
can you check if pavucontrol runs, because pamix cant connect to your pulse server

**Comment by Polynomial-C** [comment]
You're right, somehow pamix fails to connect to pulse server when I try to start it in an ssh-session which has the DISPLAY variable set to `localhost:11.0`.
As soon as I run `DISPLAY="" pamix` or unset DISPLAY variable, pamix can connect.
May I suggest a better error handling in this case? Because right now, when pamix fails like this the shell is unuseable until I execute `reset`. Perhaps some user friendly error message would be great, too.

**Comment by patroclos** [comment]
yeah, i had the same issue with ssh, but since i run pulseaudio as a deamon that wasn't an issue anymore.
Also im gonna add some errorhandling shortly
