### ISSUE TITLE
Opening pamix on Debian buster sometimes hangs playback for roughly a second until it connects

### ISSUE THREAD

**Issue by patroclos** [patroclos/PAmix#50]
maybe this could be related to the autospawn setting

**Comment by patroclos** [comment]
This issue also exists with pavucontrol, seems to be related to my pulse settings after all

**Comment by 0x0D15** [comment]
I also have a similar problem, it is likely a pulseaudio bug as I have multiple machines which all experience the same delay.

**Comment by patroclos** [comment]
I don't have this issue on Arch, so it's definitely some pulse configuration problem
