### ISSUE TITLE
blank screen under unknown circumstances

### ISSUE THREAD

**Issue by 532910** [patroclos/PAmix#59]
Sometimes it stops work and I see just a blank screen. PAmix doesn't crash, it continues to be running.
I don't know how to reproduce this. Just leave it working for a long time.

**Comment by patroclos** [comment]
I'm aware of this one, I'll see what I can do about this.

**Comment by patroclos** [comment]
Just pushed the dev branch. I've run this build for the past few days and didn't run into this issue anymore

**Comment by 532910** [comment]
What is the reason the bug-resize-segfault isn't merged?

**Comment by patroclos** [comment]
it's merged into the dev branch.
I'm closing this issue, feel free to reopen if this problem persists for you on the dev branch

**Comment by 532910** [comment]
Nope, bug-resize-segfault still isn't merged

**Comment by patroclos** [comment]
![1594051287](https://user-images.githubusercontent.com/5959583/86614075-bdf11a00-bfb2-11ea-8e21-4404bc847a16.png)

the fuck are you talking about

**Comment by 532910** [comment]
I've missed it with master

**Comment by 532910** [comment]
Not fixed, please reopen.

**Comment by patroclos** [comment]
I got another blackscreen aswell, the current changes on dev should address that one too.
It was again related to the same function.

**Comment by 532910** [comment]
Looks like the most frequent trigger for this issue is youtube scrolling.

**Comment by 532910** [comment]
Wow, is it fixed in master? Can I test it?

**Comment by patroclos** [comment]
it's fixed in dev, gonna merge into master soon
